### PR TITLE
fix: don't show carnets as inspectable when sent to others

### PR DESCRIPTION
**Pull request by rosvik**
ref. https://mittatb.slack.com/archives/C0116FMPX4Y/p1710495503900459

## Sending side / receiving side
<div>

</div>

### CODE REVIEW

**Review by gorandalum — APPROVED** [review]
Ok as a quick fix now :+1:

**Review by reidzeibel — APPROVED** [review]
LGTM, sorry I didn't do a thorough check on the sent carnet tickets!

**Comment by rosvik** [comment]
Made an issue for refactoring ValidityHeader: https://github.com/AtB-AS/kundevendt/issues/17309

**Comment by tormoseng** [comment]
Looks good!

**Pull request merged**
