### PR TITLE
fix: use a different leg line color when the organization is fram.

### PR DESCRIPTION
**Pull request by jonasbrunvoll**
Closes https://github.com/AtB-AS/kundevendt/issues/15463

#### Background
The leg line color in dark mode in the FRAM app is currently not visible.

#### Illustrations
<details>
<summary>screenshots/video/figma</summary>

|      | Current solution |  Proposed solution    |
| :---:        |    :----:   |         :---: |
| Light mode      | Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-22 at 10 19 18      | Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-22 at 10 19 49   |
| Dark mode  | Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-22 at 10 19 57       |  Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-22 at 10 19 06  |

</details>

### Proposed solution
Use a different leg line color when the organization is FRAM. 

### Acceptance Criteria
- [ ] Leg line is visible in the FRAM app in both light and dark mode. 
- [ ] The fix does not affect the leg line color selection of other oragnaization than FRAM.

### CODE REVIEW

**Review by marius-at-atb — APPROVED** [review]
Lgtm. Nice PR description!
I would suggest creating a variable for this color and reuse it in all 3 places.

**Review by gorandalum — CHANGES_REQUESTED** [review]
This is a problem with the colors in the design-system, and not a problem in the app. I'll do a quick talk with our designer to see how we can fix this.

**Comment by gorandalum** [comment]
The background colors for dark mode for Fram in the design system needs to be changed. They must follow the same pattern as the AtB colors where it is a gradient from darker colors to ligher colors. Different background colors are placed upon each other, and  having `background_0` the same as `background_3`, and `background_1` the same as `background_2` won't work with our components.

Screenshot 2024-05-22 at 13 35 01

**Comment by jonasbrunvoll** [comment]
Mhm, I see. Updating the background colors of the FRAM in dark mode should be a separate task. The question is who will take responsibility for updating the colors. In addition to examining how an update in the background colors will affect the appearance of the app, it must also be examined how it will affect `planner-web`.

**Comment by jorelosorio** [comment]
I would rather change the color in the theme and not inside the code with conditionals if that is possible 👍

**Comment by gorandalum** [comment]
To clarify, this shouldn't be merged. It should be fixed in the design system. I think changing it in the design-system shouldn't be too risky, but having the colors as they are now are risky.

**Comment by jonasbrunvoll** [comment]
This issue will be solved when updating the colours in the design system. I therefore close this PR.

**Pull request closed without merging**
