### PR TITLE
fix: use small padding around icons in travel search results

### PR DESCRIPTION
**Pull request by rosvik**
This adds some more padding around transport icons in travel search ResultItems.

I was unsure about what kind of prop I should use here, so I'm open to feedback 😊 

1. I could use ContainerSizingType (`'compact' | 'standard' | 'spacious'`), but it didn't quite fit since all I needed was two modes, and default would be compact. 
2. A new prop `type='normal' | 'spacious'`. The `mode` name is taken for Transport Mode.
3. I felt like `spacious=boolean` was the simplest solution, but it doesn't really fit what we've done elsewhere

fixes https://github.com/AtB-AS/kundevendt/issues/3834#issuecomment-1943696655

### CODE REVIEW

**Review by gorandalum — COMMENTED** [review]
Why not use `xSmall` padding on the other boxes in the travel search results as well? Discussed that with design? I think they are "transportation boxes" as well, and it would be beneficial to have same look and feel throughout the app.

**Comment by rosvik** [comment]
> Why not use `xSmall` padding on the other boxes in the travel search results as well? Discussed that with design? I think they are "transportation boxes" as well, and it would be beneficial to have same look and feel throughout the app.

@gorandalum That's an option, but I don't think that's a good solution in this case:

- I think these have more in common with "LineChip" in departures, than the other transport icons (although it is implemented differently), so we might want to look at those together.
- The icon width grows as the text below gets longer, so we end up with very long icons like this in some cases, which is a bit odd looking:
Screenshot 2024-02-14 at 14 59 38

But @oyvindmikkelsenatb or @ckbilstad, do you have any opinions?

**Comment by jorelosorio** [comment]
I could suggest using an attribute as padding and use xsmall, medium, large... as we have it, it might that spacious alone might not be clear.

**Comment by gorandalum** [comment]
I'll ask @oyvindmikkelsenatb in the office here, conclusions incoming.

**Comment by gorandalum** [comment]
He said we should have two different variations of the padding. Suggested "compact" and "standard", where "compact" is the `xSmall` padding.

**Comment by rosvik** [comment]
@gorandalum Sounds good! So in typescript, I could set `type='compact' | 'standard'` where default is `'compact'`?

**Review by gorandalum — APPROVED** [review]

**Pull request merged**
