### PR TITLE
feat: update android side dependencies and fix flipper android

### PR DESCRIPTION
**Pull request by reidzeibel**
This PR will merge my fix for Android Dependencies for Jorge's branch in this PR https://github.com/AtB-AS/mittatb-app/pull/4368.

@jorelosorio if you find this working, you can approve and merge it to your branch :)

~~**NOTE: TSC failures should be fixed on Jorge's branch, this PR is only handling the Android part, there's one package.json update about Babel, because the build was failing due to some issues with babel, after I added that part, it works.**~~

Fixed the tsc issues!

### CODE REVIEW

**Review by gorandalum — COMMENTED** [review]
Do you have any documentation or comments regarding why flipper now shouldn't just be a `debugImplementation`?

**Comment by reidzeibel** [comment]
@gorandalum good point, I was just following the steps mentioned here : https://react-native-community.github.io/upgrade-helper/?from=0.72.4&to=0.73.5

I reverted to `debugImplementation` and it still works

**Comment by gorandalum** [comment]
> @gorandalum good point, I was just following the steps mentioned here : https://react-native-community.github.io/upgrade-helper/?from=0.72.4&to=0.73.5
> 
> I reverted to `debugImplementation` and it still works

That migration guide was enough for me. Can't really know if using `debugImplementation` works before testing a non-debug build, like staging or prod.

**Review by gorandalum — APPROVED** [review]

**Review by rosvik — APPROVED** [review]
LGTM

**Review by jorelosorio — APPROVED** [review]

**Pull request merged**
