### PR TITLE
feat: remove user profile description overrides

### PR DESCRIPTION
**Pull request by rosvik**
This removes custom overrides to traveller descriptions, which means that traveller categories always have the same description across different ticket types.

Ref. discussion here: https://mittatb.slack.com/archives/C025NUF4WA0/p1717676040969969

closes part of https://github.com/AtB-AS/kundevendt/issues/15528

### Acceptance criteria

- [ ] Description of traveller categories still show up where they did before, but have the same description for all ticket types.
	- No more mention of validity on bike or night bus.
- [ ] Screen reader works like before.

### CODE REVIEW

**Review by gorandalum — APPROVED** [review]
Great!

**Comment by rosvik** [comment]
Thanks for review, but I'm waiting for this discussion to be resolved before we can merge this: https://mittatb.slack.com/archives/C025NUF4WA0/p1717676040969969

**Review by mortennordseth — APPROVED** [review]
I've verified with the PO at Nordland that we can remove these texts

**Comment by HanneLH** [comment]
Tested ok on AtB ✅

**Pull request merged**
