### PR TITLE
fix: updating the wrong departure in favorite departures with realtime data

### PR DESCRIPTION
**Pull request by mortennordseth**
To prevent us from updating the wrong departure in favorite departures with real-time data for another departure, I've added a check on `aimedDepartureTime`. This change was necessary because departures have the same `serviceJourneyId`, which caused the app to update the wrong departure in the user's favorite departures list. 

See https://github.com/AtB-AS/atb-bff/pull/279 for necessary changes to the bff. 

Closes https://github.com/AtB-AS/kundevendt/issues/4277

### CODE REVIEW

**Comment by rosvik** [comment]
Does this apply to cases like Ringen in Oslo as well, where the same journey passes the same stop several times?

Would a better solution be to return `aimedDepartureTime` for realtime data from the BFF, so that we always have an unique identifier for each departure?

**Comment by mortennordseth** [comment]
If the journey has the same `serviceJourneyId` it does. 

That's probably a better solution. Maybe we could make a unique identifier using the service date and serviceJourneyId, `datedServiceJourneyId` (e.g. "2023‐06‐30_ATB:ServiceJourney:73_200329232360547_37_200109141539610")?

What are the consequences of adding a new field to the BFF, @rosvik? Do we need a new version (v3) of the endpoint?

**Comment by rosvik** [comment]
Ringen does have the same ID, yes. It also passes the same stop twice in less than an hour, so just the date isn't enough to identify it. Other places, we have used the full `aimedDepartureTime + serviceJourneyId` to account for this, since this doesn't change with delays, and is unique no matter how frequent the departure is. See here: https://github.com/AtB-AS/mittatb-app/blob/master/src/place-screen/components/QuaySection.tsx#L175

It's safe to add new fields to BFF endpoints without making a new version 👍

**Comment by mortennordseth** [comment]
Updated with a better solution that also works for "Ringen", thanks to @rosvik 🎉 PR for the changes to the BFF: https://github.com/AtB-AS/atb-bff/pull/279.

**Review by rosvik — APPROVED** [review]
Looks good 💯

**Pull request merged**
