### PR TITLE
feat: highlight Vipps login on LoginOptionsScreen

### PR DESCRIPTION
**Pull request by rosvik**
ref. https://github.com/AtB-AS/kundevendt/issues/17792

### CODE REVIEW

**Review by gorandalum — APPROVED** [review]
Looks good! Has a designer taken a look, and updated Figma?

**Comment by rosvik** [comment]
@gorandalum 
> Looks good! Has a designer taken a look, and updated Figma?

Yes, this is based on sketches from @oyvindmikkelsenatb. We thought it didn't make sense to update Figma, since this should be a temporary change, and be reverted after May.

**Comment by reidzeibel** [comment]
Will this affect the OMS as well @rosvik ?

**Comment by gorandalum** [comment]
> We thought it didn't make sense to update Figma, since this should be a temporary change, and be reverted after May.

Aha, I missed the part that this is temporary. On my part I don't see why it should be temporary if Vipps is the more reliable option.

**Comment by rosvik** [comment]
SMS _shouldn't_ be a less reliable method, so I think it makes sense to keep it as a primary option once we're not concerned about the quota. But we can come back to that for the next release.

**Comment by mortennordseth** [comment]
> @mortennordseth / @jonasbrunvoll / @mikaelbr Is this OK behavior for you for one app release? As mentioned above, this will be reverted after May.

Ok 👍

**Comment by HanneLH** [comment]
Tested ok ✅

**Pull request merged**
