### PR TITLE
fix: missing accessible for android

### PR DESCRIPTION
**Pull request by marius-at-atb**
Fix for android, see [comment here](https://github.com/AtB-AS/mittatb-app/pull/4230/files/04c722a41280339fe713a4b85f69403ba2178c31#r1453319773)

Resolves https://github.com/AtB-AS/kundevendt/issues/8619

### CODE REVIEW

**Review by gorandalum — APPROVED** [review]

**Comment by gorandalum** [comment]
And one more thing, have you tested it on Android? Might need `collapsable={false}` as well.

**Comment by marius-at-atb** [comment]
@gorandalum In the android simulator it crashes without `accessible`, but not when it is added.
So `collapsable={false}` doesn't seem to be necessary, but should we add it anyway?

**Comment by gorandalum** [comment]
Yeah, I think it only crashed in staging without it. Might create an `AccessibleView` or something for this, where ref is mandatory and it sets accessible and collapsable correctly.

**Comment by tormoseng** [comment]
Tested OK!

**Pull request merged**
