### PR TITLE
fix: make expanded part of expandable section item accessible

### PR DESCRIPTION
**Pull request by hanne-at-atb**
The screen reader can now access and read out the content of the expanded section in ExpandableSectionItem, both on android and iOS 👾 

Fixed as part of: https://github.com/AtB-AS/kundevendt/issues/16299
Also closing the reported bug: https://github.com/AtB-AS/kundevendt/issues/10098

### CODE REVIEW

**Review by rosvik — APPROVED** [review]

**Review by gorandalum — COMMENTED** [review]
Tested both on iOS and Android? My experience is that nested accessible doesn't play well on iOS.

**Comment by marius-at-atb** [comment]
Doesn't seem to work on my iPhone 15

**Comment by hanne-at-atb** [comment]
> Tested both on iOS and Android? My experience is that nested accessible doesn't play well on iOS.

Tested on android 😢 Will look into it!

**Review by gorandalum — APPROVED** [review]
One tip: Sit together with tester and show them the solution locally to decide if it's good enough (if you haven't already). The feedback loop is much faster then than it going back and forth in test.

**Pull request merged**
