### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by mikaelbr**
Not bumping Firebase dependencies as this
requires bump for cocopods to 1.10.0 which
is not supported by AppCenter as of now.

Still uses eslint-plugin-react-native@3.8.1 due to https://github.com/Intellicode/eslint-plugin-react-native/issues/270

### CODE REVIEW

**Comment by mikaelbr** [comment]
I think this is something best reviewed by running locally

**Comment by cbrevik** [comment]
I'm having some trouble testing on Android (something up with my dev env), but have you tested the changes on Android?

**Comment by mikaelbr** [comment]
I did. But I had to clear the cache and do some aggressive cleaning. I hoped it would be better for others or with a clean install.

**Review by cbrevik — APPROVED** [review]
Worked fine for me on iOS 🙆🏻‍♂️

**Comment by gorandalum** [comment]
Worked for me on Android Simulator

**Review by gorandalum — APPROVED** [review]

**Pull request merged**
