### PR TITLE
feat: show cancelled trips in departures section

### PR DESCRIPTION
**Pull request by Nisha1306**
resolves https://github.com/AtB-AS/mittatb-app/issues/2695

### CODE REVIEW

**Review by monopoint — CHANGES_REQUESTED** [review]
components/cancelled-departure should be moved to TripDetails/Components
also we should move Pagination to TripDetails/components because it's not really reusable outside trips

**Comment by Nisha1306** [comment]
> components/cancelled-departure should be moved to TripDetails/Components also we should move Pagination to TripDetails/components because it's not really reusable outside trips

Migrated to relevant directories 👍

**Comment by monopoint** [comment]
Talk Back does not inform users that the departure is cancelled:
image

**Comment by Nisha1306** [comment]
> Talk Back does not inform users that the departure is cancelled: image

Fixed this 👍

**Review by monopoint — APPROVED** [review]
great! looks good!

**Pull request merged**
