### PR TITLE
refactor: Don't load user benefits if no operator benefits are offered

### PR DESCRIPTION
**Pull request by KristianSelnas**
Closes https://github.com/AtB-AS/kundevendt/issues/15779

Background: Operator benefits are loaded from Firebase through a context. Which operator benefits a user is eligible (user benefits) are loaded from the backend. First of all it's unnecessary to load user benefits if there are no provided operator benefits, but that's really a just a matter of saving one request (the result is cached).  However, FRAM and NFK don't have the functionality for loading user benefits installed in their environment, and loading user benefits will therefore result in an error.

The proposed solution loads user benefits only if there are operator benefits available.

This PR will be in conflict with https://github.com/AtB-AS/mittatb-app/pull/4049. I suggest merging 4049 first and then revisit this one.

### CODE REVIEW

**Comment by reidzeibel** [comment]
@KristianSelnas #4049 is merged, yay!

**Comment by KristianSelnas** [comment]
Thanks @reidzeibel. I'll see if I can work out the conflicts, then 😓

**Comment by reidzeibel** [comment]
@KristianSelnas you want me to do the conflict resolution? I think I can do it 😄

**Comment by KristianSelnas** [comment]
> Thanks @reidzeibel. I'll see if I can work out the conflicts, then 😓

Sure! Be my guest 👍

**Comment by KristianSelnas** [comment]
@reidzeibel Looks good. I don't see any apparent merge errors at least.

**Review by gorandalum — APPROVED** [review]
LGTM :+1:

**Pull request merged**
