### PR TITLE
feat: Enable nynorsk for all orgs

### PR DESCRIPTION
**Pull request by gorandalum**
### Acceptance criteria
- [ ] Possible to turn on Nynorsk in prod also for non-debug users

### CODE REVIEW

**Review by marius-at-atb — APPROVED** [review]
Ein siger for nynorsken 🇳🇴

**Comment by gorandalum** [comment]
Ok? @Sebstorvik

**Comment by Sebstorvik** [comment]
Will it still only be for debug users or will this make it available for everyone?

**Review by rosvik — APPROVED** [review]
🎉 🇳🇴

**Comment by gorandalum** [comment]
> Will it still only be for debug users or will this make it available for everyone?

Isn't it obvious from the code changes? 😄 Nynorsk for everyone! Currently it is only available for debug-users, except for Fram.

**Pull request merged**
