### PR TITLE
fix: replace activeTintColor in TabNavigator

### PR DESCRIPTION
**Pull request by toretefre**
Fixes invisible active tab in NFK-app in combination with design-system PR: https://github.com/AtB-AS/design-system/pull/41

With the changes in the design system from here: https://github.com/AtB-AS/design-system/pull/41 the app looks like this:

Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 11 16 06
Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 11 15 57
Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 11 06 27
Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 11 05 24

### CODE REVIEW

**Comment by mikaelbr** [comment]
This is probably something you can see if makes sense or not, @rosvik ?

**Comment by rosvik** [comment]
I'm not sure if the colors here made sense in the first place 😅 I don't think your changes make this a lot better or worse, so I'm not opposed to it, but isn't the contast here a problem?

Screenshot 2022-05-11 at 11 42 27

An option that looks identical for AtB, but makes a little more sense design system-wise, is this: 

```
labelPosition: 'below-icon',
activeTintColor: theme.interactive.interactive_2.outline.background,
inactiveTintColor: theme.text.colors.secondary,
style: {
  backgroundColor: theme.interactive.interactive_2.default.background,
  ...useBottomNavigationStyles(),
},
```

How does that look for NFK?

**Comment by toretefre** [comment]
`interactive_2.outline.background` does not currently seem to be used anywhere else in the app, so if that works for AtB, I have corrected the NFK color to #FFFFFF (as it was intended to be).

**Comment by toretefre** [comment]
With #FFFFFF as `interactive_2.outline.background` at NFK, the app looks like this:
Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 12 58 11
Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 12 51 53
Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 12 51 46

Simulator Screen Shot - iPhone 13 Pro - 2022-05-11 at 12 58 17

**Comment by rosvik** [comment]
> `interactive_2.outline.background` does not currently seem to be used anywhere else in the app

It is used in `RadioSegments`, as part of ticketing 2.0, and will be part of other ticketing components as well. You might encounter issues there with #FFFFFF. 

Screenshot 2022-05-11 at 14 18 30


Another option is to create a new color in the design system with the color values we want.

**Review by rosvik — APPROVED** [review]
LGTM if it looks good to you.

**Pull request merged**
