### PR TITLE
fix: Update Beacons context to handle better status updates

### PR DESCRIPTION
**Pull request by jorelosorio**
This PR handles a case where the `KettleInfo` state changed due to a revoke, onboard but the `useEffect` was not aware of it, so it did not trigger start again the beacons, so `kettleInfo` had to be added in the deps list in order to know if it is running or not and depending on changes, and be able to start it again.

### CODE REVIEW

**Comment by tormoseng** [comment]
🟢  Tested to turn on beacons through the privacy page: Beacons status was then `Running`

🔴  Can't seem to get announcements to work after seeing the onboarding and allowing all permissions. The status is `Running`. Handle in separate issue https://github.com/AtB-AS/kundevendt/issues/16286

🔴  Pt. 1 in this [issue](https://github.com/AtB-AS/kundevendt/issues/16140) is still not handled. Handle in separate issue https://github.com/AtB-AS/kundevendt/issues/16285

**Review by marius-at-atb — APPROVED** [review]
Lgtm!

**Review by gorandalum — COMMENTED** [review]
The PR comment mentions something about revoking, but I don't really understand that part by looking at the code. The user has revoked a consent, and that should trigger something?

**Comment by jorelosorio** [comment]
> The PR comment mentions something about revoking, but I don't really understand that part by looking at the code. The user has revoked a consent, and that should trigger something?

I mentioned revoking as an action that needs to trigger an update but when the user tried onboard again, nothing have changed after revoking, therefore the start never happened. I did not change something on revoking, but they way how it reacts after onboarding again.

**Comment by tormoseng** [comment]
👍

**Pull request merged**
