### PR TITLE
feat:optional new front page with dashboard

### PR DESCRIPTION
**Pull request by monopoint**

### CODE REVIEW

**Comment by mikaelbr** [comment]
Is this a collection of changes or is it connected to one particular issue? What is the scope of this?

**Review by gorandalum — CHANGES_REQUESTED** [review]
Looks good! And we should get this into master as soon as possible. However I would really like to align the naming of the frontpage/dashboard feature. It is an unnecessary naming change when going from issues to code. So either:
- Also use frontpage in app (instead of dashboard)
- Rename issues in Github and conform with the team that we use the term "dashboard" going forward.

**Comment by mikaelbr** [comment]
Is this for this https://github.com/AtB-AS/kundevendt/issues/1876 ?

**Comment by monopoint** [comment]
> Is this for this [AtB-AS/kundevendt#1876](https://github.com/AtB-AS/kundevendt/issues/1876) ?

yes

**Comment by monopoint** [comment]
This was'n really meant as a code review, ass all code has been reviewed and approved in their respective PR. The PRs are merged into this, conflicts resolved, and I wanted @gorandalum to have an opportunity to see what was being merged into master.

**Comment by monopoint** [comment]
we decided to keep "Dashboard" as component name for now.

**Review by gorandalum — APPROVED** [review]

**Review by jorelosorio — APPROVED** [review]

**Pull request merged**
