### PR TITLE
test: more visual tests

### PR DESCRIPTION
**Pull request by tormoseng**
Added some more visual tests. Currently there are these tests:
- Departures (overview, details, single elements, journey aid)
- Profile (notifications, default traveller)
- Tickets overview
- Single ticket (overview, select traveller, ticket info, flex discount, purchase summary w/wo payment choice)
- Night ticket (overview, no descriptions, ticket info)
- Travel Search (results, details)
- Frontpage

Also, added handling of whether login is presented or not.

### CODE REVIEW

**Review by gorandalum — APPROVED** [review]

**Comment by reidzeibel** [comment]
@tormoseng just curious but how does this test work?

**Comment by tormoseng** [comment]
✅  Tests OK: https://github.com/AtB-AS/mittatb-app/actions/runs/12408798950

**Comment by tormoseng** [comment]
> @tormoseng just curious but how does this test work?

@reidzeibel The tests are walking through the app and at specific given "states", a screenshot is taken that is compared to a baseline image. If there are any differences, a value is given based on how much difference there is. At the moment I don't tolerate any difference. Also, a screenshot of the diffs are given as artifacts from the run.

<details>
<summary>Example when running the tests with different font size</summary>

frontpage-android-1080x2340

</details>

**Pull request merged**
