### PR TITLE
fix: Change loading screen texts for FRAM

### PR DESCRIPTION
**Pull request by adriansberg**
Change loading screen texts for FRAM

Closes https://github.com/AtB-AS/kundevendt/issues/8785

### CODE REVIEW

**Review by toretefre — APPROVED** [review]
Nice! Also need to change the url, not sure where it is done

**Comment by adriansberg** [comment]
Same case as with the ticket page. The URL is in Remote Config, so it won't be fetched in offline mode.

**Comment by mortennordseth** [comment]
> Same case as with the ticket page. The URL is in Remote Config, so it won't be fetched in offline mode.

Maybe we could move the default customer service URL to the env-file, similar to what is done with the privacy policy URL?

**Comment by adriansberg** [comment]
Great idea. I'll do that. Do any of you have access to the other tenants and get their customer service url?

**Comment by mortennordseth** [comment]
I got these from the remote config: 

NFK: https://www.reisnordland.no/kontaktskjema
AtB: https://www.atb.no/kontakt/
FRAM: https://frammr.no/kontakt-oss

**Comment by adriansberg** [comment]
Different for the english pages, right?

**Comment by toretefre** [comment]
https://www.reisnordland.com/contact-us
https://www.atb.no/en/customer-service/
https://en.frammr.no/contact-us

**Comment by mortennordseth** [comment]
They do exist in English, but afaik that's not supported by the app today?

**Comment by adriansberg** [comment]
Right. Used to the webshop having both.

**Comment by adriansberg** [comment]
Added it now.

**Comment by toretefre** [comment]
So, we are now trying Firestore first, and then defaulting to env url, right?

**Comment by adriansberg** [comment]
As I understand it the default is now set through the .env, and then Remote Config have precedence over the default that is set.

**Comment by adriansberg** [comment]
https://github.com/AtB-AS/mittatb-app/pull/3871/commits/3ed3956a380a568f493b51f8157529cb0970c24c should fix the ticketing page being shown in offline mode.

**Review by toretefre — APPROVED** [review]

**Pull request merged**
