### PR TITLE
build: Split update devices job to be run in serial

### PR DESCRIPTION
**Pull request by jorelosorio**
There was an issue while update devices ran at the same time to update provisioning profiles, it was separated in order to make it serialized, first development then adhoc.

Before:

image

Now:

image

### CODE REVIEW

**Comment by reidzeibel** [comment]
Changes looks fine, but shouldn't this be a `chore` instead of `fix`? because this is not a fix for the app but a chore to fix the build flow.

**Comment by jorelosorio** [comment]
> `chore` instead of `fix`

I named it fix because even that the job ends successful, it was not able to push the changes in the git repo for new devices, so when a build was made the new device was not found because the provisioning profiles do not have the updated device.

**Review by reidzeibel — APPROVED** [review]

**Comment by rosvik** [comment]
There's also `build` 🤓 https://github.com/AtB-AS/mittatb-app/blob/master/CONTRIBUTING.md#not-included-in-changelog

**Comment by tormoseng** [comment]
Nice! Test: https://github.com/AtB-AS/mittatb-app/actions/runs/10417698159

**Pull request merged**
