### PR TITLE
refactor: Merged ZoneSymbol and NotInspectableSymbol

### PR DESCRIPTION
**Pull request by gorandalum**
They were two components with two different implementations, although
they should look mostly the same. Also they were in two separate places
in the GUI, but after talking with Christian, it was decided they can be
presented at the same place.

Fixes https://github.com/AtB-AS/kundevendt/issues/330

### CODE REVIEW

**Comment by gorandalum** [comment]
Changed in Figma so the not-inspectable symbol is at the same place as the inspectable symbol:
Screenshot 2022-08-31 at 15 43 16

**Comment by gorandalum** [comment]
Etter fix:
Screenshot 2022-08-31 at 16 21 27

**Review by jorelosorio — APPROVED** [review]
LGTM

**Review by rosvik — APPROVED** [review]
Looks good! 💯

**Pull request merged**
