### PR TITLE
fix: Fix an issue while migrating filters from old versions to new versions

### PR DESCRIPTION
**Pull request by jorelosorio**
There was a case where filter were not fully migrated, after review from @tormoseng 

Fixes: https://github.com/AtB-AS/kundevendt/issues/3857#issuecomment-1547365503

### CODE REVIEW

**Review by gorandalum — CHANGES_REQUESTED** [review]
I think this can be done some other way. Checking with `Array.isArray` makes the typing as `any[]` which is kinda imprecise. You should check the type of `oldStoredFilters`, I think that is the actual culprit.

**Comment by jorelosorio** [comment]
> I think this can be done some other way. Checking with `Array.isArray` makes the typing as `any[]` which is kinda imprecise. You should check the type of `oldStoredFilters`, I think that is the actual culprit.

Inside getFilters there is a cast as the object is needed.

```
return (
      userFilters ? JSON.parse(userFilters) : {}
    ) as TravelSearchFiltersSelectionType;
```

**Comment by gorandalum** [comment]
> Inside getFilters there is a cast as the object is needed.

Yes, but it is cast to `TravelSearchFiltersSelectionType` also for old filters, which is not the correct type.

**Comment by jorelosorio** [comment]
> > Inside getFilters there is a cast as the object is needed.
> 
> Yes, but it is cast to `TravelSearchFiltersSelectionType` also for old filters, which is not the correct type.

Ok, I got it and made a refactor to it :)

**Review by gorandalum — CHANGES_REQUESTED** [review]

**Review by gorandalum — APPROVED** [review]

**Pull request merged**
