### PR TITLE
feat: update RNMapBox dependency and update usage of UserLocation

### PR DESCRIPTION
**Pull request by reidzeibel**
Replaces PR : https://github.com/AtB-AS/mittatb-app/pull/4141
Closes : https://github.com/AtB-AS/kundevendt/issues/16093

This PR updates the RNMapBox dependency to fix the issue with using `UserLocation` with `onMapIdle` on Android.

Also replaces the deprecated `UserLocation` with the new `LocationPuck` as suggested by RNMapBox (`NativeUserLocation` is also deprecated).

~~iOS users might have to run `pod update MapboxMaps` before `pod install` for it to be able to run. Please let me know if I need to update something regarding this issue.~~ just pod install should work now, I have updated the podfile.lock.

Screenshots: 

Android: 
image

iOS: 
image

### CODE REVIEW

**Comment by KristianSelnas** [comment]
I guess you should run `pod install` and include the updated `Podfile.lock` in this PR as well

**Comment by reidzeibel** [comment]
Added the updated podfile.lock

**Review by marius-at-atb — APPROVED** [review]
Great solution!

**Review by KristianSelnas — APPROVED** [review]
Good job on figuring this issue out 👏

**Pull request merged**
