### PR TITLE
refactor: Stack hierarchy and screen reuse

### PR DESCRIPTION
**Pull request by gorandalum**
This is done in context of the new screen/stack documentation added here:
https://github.com/AtB-AS/docs-private/pull/9

### CODE REVIEW

**Comment by jorelosorio** [comment]
🫣

**Review by rosvik — APPROVED** [review]
Didn't spend time to review this in detail, but I think it looks good overall 👌

**Comment by tormoseng** [comment]
@gorandalum Using the `Back` button in Departures has a different effect than before. Before, if you had navigated to different stop places through the detailed view, you could navigate back to the previous and then again to the provios. Now, `Back` leads you straight to the initial stop place. See the screen recordings below.

<details>
<summary>Prevous navigation in departures</summary>

https://user-images.githubusercontent.com/5812433/213999754-3d5d5d92-7c7b-40e6-8335-27008085c2a3.mp4

</details>

<details>
<summary>New navigation in departures</summary>

https://user-images.githubusercontent.com/5812433/213999663-b2887468-c08e-469b-9c4b-4d874524037b.mp4

</details>

**Comment by tormoseng** [comment]
@gorandalum 
If I start a new travel search, everything seems fine. Then I try to change place of departure or arrival. I choose from recent results/searches/locations. The only thing that happens then is that the chosen recent location pops up at the top of the recent list. It is never chosen as arrival/departure. See the screen recording attached.

<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/5812433/214055826-15699aff-2c4d-4212-8f5d-e9445868dcc4.mp4

</details>

It is neither possible to tap favorite place nor from the map (see screen recording below) - so nothing works if you want to change arrival/departure after your initial search.

<details>
<summary>Screen recording 2</summary>

https://user-images.githubusercontent.com/5812433/214058592-8ccde0cc-c41e-4652-8e57-d61d2659b829.mp4

</details>

**Comment by gorandalum** [comment]
@tormoseng https://github.com/AtB-AS/mittatb-app/pull/3235

**Comment by tormoseng** [comment]
@gorandalum 
Another observation. When doing travel search > travel details > departures, the "pick favorite departure mode" is shown with the Close button. See screen recording.

<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/5812433/214265941-eb9b4071-a902-4a6f-9133-7581d28a054a.mp4

</details>

**Comment by HanneLH** [comment]
@gorandalum 
Legge til favoritt, etter du har valgt favoritt avgang og klikker lukk, så blir du send til endre favoritt siden og ikke forsiden, som forventet.
https://user-images.githubusercontent.com/104772494/214283186-86a039a7-e203-4a3e-b67c-889d4502532f.MP4

**Comment by gorandalum** [comment]
Both of these last comments is (hopefully) fixed here:
https://github.com/AtB-AS/mittatb-app/pull/3239

**Comment by HanneLH** [comment]
@gorandalum 
Ved legge til favoritter, og skal åpne for å "se flere avganger" så kommer jeg inn på avgangsvisningen: 
<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/104772494/214579214-7635c9aa-6c70-4f7b-8797-bce206627831.mp4

</details>

**Comment by gorandalum** [comment]
> @gorandalum Ved legge til favoritter, og skal åpne for å "se flere avganger" så kommer jeg inn på avgangsvisningen:

Blir fikset her: https://github.com/AtB-AS/mittatb-app/pull/3243

**Comment by tormoseng** [comment]
@gorandalum 
Not sure if this observation is due to the screen refactor or dependency update, but I don't think I noticed this before the fixes.. Anyhow, if you choose depart later / arrive at, the arrival and destination disappears. 

<details>
<summary>Disappearing arrival/departure</summary>

https://user-images.githubusercontent.com/5812433/214936580-c9dcde18-fad2-4e45-aa22-3815a4789cc8.mp4

</details>

And following up on the observation above, if you then want to put in an arrival (or departure), you get stuck. The app does not react and you need to close it.

<details>
<summary>Stuck</summary>

https://user-images.githubusercontent.com/5812433/214936617-e97fa561-8c25-4454-88f0-4a780315f6bd.mp4

</details>

**Comment by gorandalum** [comment]
> **New observation:** Not sure if this observation is due to the screen refactor or dependency update, but I don't think I noticed this before the fixes.. Anyhow, if you choose depart later / arrive at, the arrival and destination disappears.

That the from/to locations are removed will be fixed by this PR: https://github.com/AtB-AS/mittatb-app/pull/3249

I couldn't reproduce the stuck error, but hopefully this fix will ensure it doesn't happen.

**Comment by tormoseng** [comment]
Tested OK on Android. Waiting for a proper iOS build.

**Pull request merged**
