### PR TITLE
fix: ACCESS_COARSE_LOCATION option for Android manifest

### PR DESCRIPTION
**Pull request by brorhb**
Potential fix for https://github.com/AtB-AS/mittatb-app/issues/1792

> On Android 12 (API level 31) or higher, users can request that your app retrieve only approximate location information, even when your app requests the ACCESS_FINE_LOCATION runtime permission.

> To handle this potential user behavior, don't request the ACCESS_FINE_LOCATION permission by itself. Instead, request both the ACCESS_FINE_LOCATION permission and the ACCESS_COARSE_LOCATION permission in a single runtime request. If you try to request only ACCESS_FINE_LOCATION, the system ignores the request on some releases of Android 12.

### CODE REVIEW

**Review by gorandalum — APPROVED** [review]
GW! Håper vi klarer å reprodusere på en eller annen mobil slik at vi får verifisert at det fungerer, men det ser lovende ut basert på doc!

**Comment by cbrevik** [comment]
https://github.com/AtB-AS/mittatb-app/blob/e1ccd6306732a8c44d9347a0195ee74852c7ffc0/src/GeolocationContext.tsx#L190 vil det ikke kreve oppdatering her også?

**Comment by cbrevik** [comment]
Og her https://github.com/AtB-AS/mittatb-app/blob/e1ccd6306732a8c44d9347a0195ee74852c7ffc0/src/GeolocationContext.tsx#L198

**Comment by brorhb** [comment]
Jo det kan hende 😁 den vil sikkert rapportere coarse 👌🏻

**Comment by brorhb** [comment]
> Og her https://github.com/AtB-AS/mittatb-app/blob/e1ccd6306732a8c44d9347a0195ee74852c7ffc0/src/GeolocationContext.tsx#L198

Vi kan be om FINE, men hvis kunden bare vil gi coarse så må vi deale med det i checken. Sånn jeg leser dokumentasjonen til location permission hvertfall 😅

**Comment by cbrevik** [comment]
Jeg klarer ikke finne en måte å reprodusere dette på, men har testet lokalt at jeg får i hvert fall satt permissions. Så tenker dette er greit nok til å QA på evt. Browserstack CC @tormoseng

**Review by cbrevik — APPROVED** [review]

**Pull request merged**
