### PR TITLE
fix: change implementation of background colors for ticketing

### PR DESCRIPTION
**Pull request by rosvik**
fixes https://github.com/AtB-AS/kundevendt/issues/2333

On the ticketing screen, the background color is now set as default to the same color as the tab, which solves the "scroll area" from being the wrong color as described in https://github.com/AtB-AS/kundevendt/issues/2333.

Also handles the case where the user has no previous purchases, which makes the "All products" section the same color as the tab.

### See proposed solution in Figma:
[Tickets / Buy](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=11562%3A50133)
[Tickets / Buy (with Recent tickets)](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=6648%3A45714)
[Tickets / Buy  (loading)](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=11562%3A50788)

### Demo

https://user-images.githubusercontent.com/1774972/196419080-fb082bf0-1762-488a-aaf4-5054e6030cad.mp4

### CODE REVIEW

**Review by Nisha1306 — APPROVED** [review]

**Review by gorandalum — CHANGES_REQUESTED** [review]
Should get this in [here](https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=6648%3A45714) as well so we don't have visual logic in the app which is not reflected in Figma. Can't really approve design changes in the app when there is no source (Figma) or history (like issue comments) to see what was decided.

**Comment by rosvik** [comment]
@ckbilstad Could you update the Figma sketches? Here's how different states (no recent tickets, loading and with recent tickets) look in the app as implemented now: 

Screenshot 2022-10-19 at 10 41 14
Screenshot 2022-10-19 at 10 40 51
Screenshot 2022-10-19 at 10 41 02

**Comment by ckbilstad** [comment]
Yes, inc soon.

**Comment by ckbilstad** [comment]
@rosvik Sketches updated. Link in description.

**Review by gorandalum — APPROVED** [review]

**Pull request merged**
