### PR TITLE
refactor: remove onboarding of departures V2

### PR DESCRIPTION
**Pull request by mortennordseth**
Closes https://github.com/AtB-AS/kundevendt/issues/3587

FRAM would like to disable the departures v2 onboarding. The remote config for this exists, but it is not used. 

AtB currently has `enable_departures_v2_onboarding` set to `false` in production. This must be set to `true` to work as today with this change. I believe this can be updated now as it is currently not in use. 

NFK does not have any value set for `enable_departures_v2_onboarding` and the default value is `false`. To work as today NFK must add the config and set it to `true`.

### CODE REVIEW

**Comment by toretefre** [comment]
Important to verify that AtB has received information that something needs to be added to Remote Config before releasing an app with this update.

**Comment by rosvik** [comment]
Could we just remove the departures onboarding completely at this point? @ckbilstad @oyvindmikkelsenatb

**Comment by toretefre** [comment]
> Could we just remove the departures onboarding completely at this point? @ckbilstad @oyvindmikkelsenatb

Think this should be alright with NFK as well

**Comment by mortennordseth** [comment]
Updated the PR to remove the departures onboarding instead of disabling it 👍

**Review by toretefre — APPROVED** [review]
I guess it's impossible to make sure that the onboarding storage key is removed from the JSON structure? Other than that it should work nicely 🚀

**Review by gorandalum — APPROVED** [review]

**Pull request merged**
