### PR TITLE
fix: use correct text color on UnknownProvider icon

### PR DESCRIPTION
**Pull request by rosvik**
Fixes some bad contrast in light mode. ([Previously it looked like this](https://mittatb.slack.com/archives/C0116FMPX4Y/p1715598607170289?thread_ts=1715346138.109749&cid=C0116FMPX4Y))

### CODE REVIEW

**Review by marius-at-atb — APPROVED** [review]

**Comment by rosvik** [comment]
**Testing:** Not much to test here, more of a heads up that I changed a text color here, that's part of the v1.51 release. Now the question mark is not black on a dark background in light mode.

**Comment by HanneLH** [comment]
@rosvik 
IMG_CE5B7BDD7C84-1
Not possible to open the report wrongly parked scooter, for both iOS and Android:
iOS V.1.51 (1715762031) 
Android: v.1.51. (1715768508)

**Comment by rosvik** [comment]
@HanneLH Right, that's a known issue ([ref. discussion here](https://mittatb.slack.com/archives/C0116FMPX4Y/p1715346138109749)). It works in prod, however. So you can download the latest version from Testflight now.

**Comment by HanneLH** [comment]
> @HanneLH Right, that's a known issue ([ref. discussion here](https://mittatb.slack.com/archives/C0116FMPX4Y/p1715346138109749)). It works in prod, however. So you can download the latest version from Testflight now.

👍🏼 
Good in test flight! 🎉

**Pull request merged**
