### PR TITLE
feat: Add nynorsk feature toggle

### PR DESCRIPTION
**Pull request by gorandalum**
### Acceptance criteria
- [ ] Nynorsk should be selectable or not in the language screen based on the feature toggle.

### CODE REVIEW

**Comment by marius-at-atb** [comment]
@Sebstorvik I don't think it makes any sense to hide a supported language?
And as this PR shows, it adds unnecessary logic to maintain..

**Comment by mortennordseth** [comment]
@marius-at-atb, NFK, and Troms do not want Nynorsk enabled in the app, so a feature flag would be nice.

**Review by marius-at-atb — APPROVED** [review]
Approving the code, although still not a fan of the feature 😛

**Comment by gorandalum** [comment]
Note that the feature is **opt-out**. Nynorsk will appear in the language menu unless `enable_nynorsk` is set to `false` in RemoteConfig.

**Comment by tormoseng** [comment]
✅  Added a RemConf in Staging and Prod.

@Sebstorvik @mortennordseth Note that if the user has nynorsk set on his/her phone, then nynorsk will also be in the app.

**Comment by mortennordseth** [comment]
Added `enable_nynorsk: false` to RemoteConfig for NFK and Svipper.

**Pull request merged**
