### PR TITLE
refactor: Change departures headers to full width

### PR DESCRIPTION
**Pull request by gorandalum**
This is to fix the issue with the missing rounded corner on the first most departure.

### CODE REVIEW

**Comment by gorandalum** [comment]
After the change the header is now full width:
<div>


</div>

**Review by rosvik — APPROVED** [review]

**Comment by gorandalum** [comment]
Acceptance criteria:
- [ ] Should be full width in all situations
- [ ] Should work when description message spans multiple lines
- [ ] Should work with large text
- [ ] Should work on both iOS and Android

**Comment by gorandalum** [comment]
Is (or will be) updated in Figma here:
https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App?node-id=6242%3A28888

**Comment by HanneLH** [comment]
Test on iOS (v.1.28 (1667919856)) og Android (v.1.28 (16679197771)) ✅

**Pull request merged**
