### PR TITLE
update: A new iOS Device for Hannah

### PR DESCRIPTION
**Pull request by jorelosorio**

### CODE REVIEW

**Review by reidzeibel — APPROVED** [review]

**Comment by tormoseng** [comment]
@hannahATB You may test to see if you see any builds after the next staging build (https://github.com/AtB-AS/mittatb-app/actions/runs/7990206602).

**Comment by tormoseng** [comment]
@jorelosorio Looks like it's still unprovisioned https://appcenter.ms/orgs/AtB-AS/apps/MittAtb-1/distribute/distribution-groups/AtB%20Internal/devices

**Comment by hannahATB** [comment]
@jorelosorio I'm not able to download the app - and I get this message on my homescreen when I try to open the app. 

IMG_0480

**Comment by jorelosorio** [comment]
@tormoseng @hannahATB I ran a new build to force use the new provisioned phones. I will notify to try to test again :).

**Comment by tormoseng** [comment]
@hannahATB Could you try to install again? Try build `1.48 (1708600879)`.

**Comment by jorelosorio** [comment]
> @hannahATB Could you try to install again? Try build `1.48 (1708600879)`.

Yes she is provisioned on that one build specifically, hopefully the cache was cleaned now, so subsequent builds will include her.

**Pull request merged**
