### PR TITLE
fix: Increase journey search input size

### PR DESCRIPTION
**Pull request by rikkekantega**
#487

Adjusted input field size and did other changes according to design (move swap button, border color change, font size etc)

Changes on margins for timepicker field (height on Fade) not included, as Christian is currently working on the Fade component.

image

### CODE REVIEW

**Comment by cbrevik** [comment]
Should this be solved with explicit height? Ref. when font sizes scale? Might `paddingVertical` not the same, while allowing to grow?

**Comment by rikkekantega** [comment]
> Should this be solved with explicit height? Ref. when font sizes scale? Might `paddingVertical` not solve the same, while allowing to grow?

Of course, you are entirely right about that. Perhaps just use minHeight instead, since we are defining this (44px) as a "minimum" touchable size. Don't want it to shrink and be harder to hit if font size is decreased.

**Comment by mikaelbr** [comment]
I think I might have accidentally touched this in #684

**Comment by rikkekantega** [comment]
> I think I might have accidentally touched this in #684

Have you solved the #487 issue entirely, or just that I'll need to consider your changes? :)

**Comment by mikaelbr** [comment]
It's equal to the height of the design in Figma which is 44. So I think so

**Comment by rikkekantega** [comment]
> It's equal to the height of the design in Figma which is 44. So I think so

Oh, shoot that I didn't know you were working on these things as well as profile. I pulled your branch now and see the new design is implemented there, I'll just close this PR. :)

**Comment by mikaelbr** [comment]
Sorry, my fault. Didn't intend to, nor is it strictly in the scope. I just started implementing the general components as a part of the new input form for adding favorites and saw that they were generic. One thing lead to another..

**Pull request closed without merging**
