### PR TITLE
fix: Updated library and services

### PR DESCRIPTION
**Pull request by jorelosorio**
After a conversation with Kogenta we need to remove the services for builds that are not meant to be compiled for kettle and add it back for those who actually are build to support beacons.

### CODE REVIEW

**Review by reidzeibel — APPROVED** [review]

**Comment by reidzeibel** [comment]
@tormoseng does it always happens or only sometimes? from what I see, it is a periodic `BroadcastIntent` which doesn't get triggered by our app, instead it is initialized by the system app (the package `com.sec.android.*` is the ones sending the broadcast). Also the intent shown by both messages are used to refresh battery stats and updating clock every minute. 

I don't think it is triggered by our app at all and these messages shouldn't be an issue. 🤔

**Comment by tormoseng** [comment]
@reidzeibel Very nice observation. I was saw a lot of 
```
11-28 14:58:23.114   974  3908 D ActivityManager: Received BROADCAST intent 0x71338db Key{broadcastIntent pkg=no.mittatb.staging intent=act=com.kogenta.kettle.LocationBroadcastReceiver cmp=no.mittatb.staging/com.kogenta.kettle.core.broadcast.LocationMotionBroadcastReceiver flags=0x2000000 u=0} requestCode=5656948 sent=0 from uid 10103
```
around the same time, but I will re-test the scenario and pay more attention to the actual sender :-)

**Comment by reidzeibel** [comment]
@tormoseng That is definitely triggered by Kogenta, I wonder if we can turn that off as well from the manifest @jorelosorio

**Comment by jorelosorio** [comment]
> @tormoseng That is definitely triggered by Kogenta, I wonder if we can turn that off as well from the manifest @jorelosorio

I not completely sure about it but, when you stop it just then stops some services to send the data or collect it, but seems like the location is still running, it might be that is just here but doing nothing, because they function "start" it does not initialize everything it uses a flag to enable send data, that is how I think works.

**Comment by reidzeibel** [comment]
@jorelosorio I see, then we should be able to just test whether it will consume more battery or not, since that broadcast should be triggered by a `location update` if the android location service is turned on. It might not affect that much though, since the broadcast is triggered but the receiver is turned off.

**Comment by tormoseng** [comment]
@reidzeibel @jorelosorio Hold your horses for a minute :-D

I re-tested now, and stopping the SDK seems to work. I don't see any brodcasts from `mittatb` nor `kogenta`. I'll test a bit more and let you know

**Comment by tormoseng** [comment]
@reidzeibel @jorelosorio 

I stopped the SDK around 09:43 today, and havn't seen any broadcasts events since. However, I see these lines from time to time. What is it - and is it something to worry about?

```
11-29 09:57:50.334 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "BEGIN IMMEDIATE;" took 0.000 ms
11-29 09:57:50.334 30404 13954 D okhttp.Http2: << 0x00000000     0 SETTINGS      ACK
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "DELETE FROM `BeaconEvent` WHERE `id` = ?" took 0.000 ms
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "DELETE FROM `BeaconEvent` WHERE `id` = ?" took 0.000 ms
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "DELETE FROM `BeaconEvent` WHERE `id` = ?" took 0.000 ms
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "DELETE FROM `BeaconEvent` WHERE `id` = ?" took 0.000 ms
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "DELETE FROM `BeaconEvent` WHERE `id` = ?" took 0.000 ms
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "COMMIT;" took 0.000 ms
11-29 09:57:50.335 30404 30903 I CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "SELECT `JailEvent`.`startTimestamp` AS `startTimestamp`, `Jai
lEvent`.`endTimestamp` AS `endTimestamp`, `JailEvent`.`startLatitude` AS `startLatitude`, `JailEvent`.`startLongitude` AS `startLongitude`, `JailEvent`.`endLatitude` AS `endL
atitude`, `JailEvent`.`endLongitude` AS `endLongitude`, `JailEvent`.`maxDistance` AS `maxDistance`, `JailEvent`.`airDistance` AS `airDistance`, `JailEvent`.`distance` AS `dis
tance`, `JailEvent`.`locationEventCount` AS `locationEventCount`, `JailEvent`.`id` AS `id` FROM JailEvent" took 0.000 ms
11-29 09:57:50.335 30404 30903 D SQLiteCursor: received count(*) from native_fill_window: 0
11-29 09:57:50.335 30404 30903 I CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
11-29 09:57:50.335 30404 30903 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "SELECT * FROM RawActivityEvent WHERE endTime <= ? ORDER BY st
artTime ASC" took 0.000 ms
11-29 09:57:50.335 30404 30903 D SQLiteCursor: received count(*) from native_fill_window: 0
11-29 09:57:50.336 30404 30904 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "BEGIN IMMEDIATE;" took 0.000 ms
11-29 09:57:50.336 30404 30904 I CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
11-29 09:57:50.336 30404 30904 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "SELECT * FROM room_table_modification_log WHERE invalidated =
 1;" took 0.000 ms
11-29 09:57:50.336 30404 30904 D SQLiteCursor: received count(*) from native_fill_window: 0
11-29 09:57:50.336 30404 30904 V SQLiteTime: /data/user/0/no.mittatb.staging/databases/com.kogenta.kettle.core: "COMMIT;" took 0.000 ms
11-29 09:57:50.336 30404 30473 V SQLiteTime: /data/user/0/no.mittatb.staging/no_backup/androidx.work.workdb: "BEGIN IMMEDIATE;" took 0.000 ms
11-29 09:57:50.336 30404 30473 I CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
11-29 09:57:50.336 30404 30473 V SQLiteTime: /data/user/0/no.mittatb.staging/no_backup/androidx.work.workdb: "SELECT state FROM workspec WHERE id=?" took 0.000 ms
11-29 09:57:50.336 30404 30473 D SQLiteCursor: received count(*) from native_fill_window: 1
11-29 09:57:50.336 30404 30473 V SQLiteTime: /data/user/0/no.mittatb.staging/no_backup/androidx.work.workdb: "DELETE from WorkProgress where work_spec_id=?" took 0.000 ms
11-29 09:57:50.336 30404 30473 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=9e81393e-efdb-451c-8b9a-f369d72c9db7, tags={ com.kogenta.kettle.core.workmanager.DataUp
loadWorker } ]
```

The reason I investigate this is if we need functionality like https://github.com/AtB-AS/kundevendt/issues/15762

**Comment by tormoseng** [comment]
@reidzeibel Mm. See that. So then we can assume that the SDK has stored some scheduled jobs in the SQLite. It seems that I get events related to `kogenta` every time I open the app from background or from "start". Could you take a look at the attached log (I've grep'ed `adb logcat` for `kogenta`)? See the latest events. I opened the app at 10:08, 10:41, 10:50:00 and 10:50:39. Seems that nothing happens when the app is open.

[log.txt](https://github.com/AtB-AS/mittatb-app/files/13498911/log.txt)

**Comment by reidzeibel** [comment]
@tormoseng I've looked into the file, there are 2 possible cases here: 

1. when app is closed, scheduled work is flagged as deleted, and deletion happens when the app is re-started.
2. when app is closed, scheduled work is deleted, and the log printing happens when the app is re-started.

Either way, I don't think this is a concern, since it is only triggered once. Would be a different story if it happens periodically though. 😄

**Comment by tormoseng** [comment]
Based on @reidzeibel conclusions, we conclude this issue as OK!

**Pull request merged**
